#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Garage")]
	public partial class DataClassesGarageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertTConsommation(TConsommation instance);
    partial void UpdateTConsommation(TConsommation instance);
    partial void DeleteTConsommation(TConsommation instance);
    partial void InsertTDetailMoteur(TDetailMoteur instance);
    partial void UpdateTDetailMoteur(TDetailMoteur instance);
    partial void DeleteTDetailMoteur(TDetailMoteur instance);
    partial void InsertTMoteur(TMoteur instance);
    partial void UpdateTMoteur(TMoteur instance);
    partial void DeleteTMoteur(TMoteur instance);
    partial void InsertTUtilisateur(TUtilisateur instance);
    partial void UpdateTUtilisateur(TUtilisateur instance);
    partial void DeleteTUtilisateur(TUtilisateur instance);
    partial void InsertTVoiture(TVoiture instance);
    partial void UpdateTVoiture(TVoiture instance);
    partial void DeleteTVoiture(TVoiture instance);
    partial void InsertTEntretien(TEntretien instance);
    partial void UpdateTEntretien(TEntretien instance);
    partial void DeleteTEntretien(TEntretien instance);
    #endregion
		
		public DataClassesGarageDataContext() : 
				base(global::Garage.Properties.Settings.Default.GarageConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGarageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGarageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGarageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGarageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TConsommation> TConsommation
		{
			get
			{
				return this.GetTable<TConsommation>();
			}
		}
		
		public System.Data.Linq.Table<TDetailMoteur> TDetailMoteur
		{
			get
			{
				return this.GetTable<TDetailMoteur>();
			}
		}
		
		public System.Data.Linq.Table<TMoteur> TMoteur
		{
			get
			{
				return this.GetTable<TMoteur>();
			}
		}
		
		public System.Data.Linq.Table<TUtilisateur> TUtilisateur
		{
			get
			{
				return this.GetTable<TUtilisateur>();
			}
		}
		
		public System.Data.Linq.Table<TVoiture> TVoiture
		{
			get
			{
				return this.GetTable<TVoiture>();
			}
		}
		
		public System.Data.Linq.Table<TEntretien> TEntretien
		{
			get
			{
				return this.GetTable<TEntretien>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCar")]
		public int DeleteCar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNumMoteur")]
		public ISingleResult<GetNumMoteurResult> GetNumMoteur([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string carburant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cylindre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> puissance)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carburant, cylindre, puissance);
			return ((ISingleResult<GetNumMoteurResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNumUser")]
		public ISingleResult<GetNumUserResult> GetNumUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<GetNumUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUser")]
		public ISingleResult<GetUserResult> GetUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string passwd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, passwd);
			return ((ISingleResult<GetUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchCar")]
		public ISingleResult<SearchCarResult> SearchCar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SearchCarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchUser")]
		public ISingleResult<SearchUserResult> SearchUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<SearchUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateUser")]
		public int UpdateUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mdp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo, nom, prenom, email, mdp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNumVoiture")]
		public ISingleResult<GetNumVoitureResult> GetNumVoiture([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numUtil, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string marque, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modele, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> annee)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numUtil, marque, modele, type, annee);
			return ((ISingleResult<GetNumVoitureResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateCar")]
		public int UpdateCar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string marque, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modele, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string couleur, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> annee)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, marque, modele, type, couleur, annee);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateMotor")]
		public int UpdateMotor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string carburant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> puissance, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cylindre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, carburant, puissance, cylindre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVoiture")]
		public ISingleResult<GetVoitureResult> GetVoiture([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<GetVoitureResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateDetail")]
		public int UpdateDetail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numMoteur, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numVoiture, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> km)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numMoteur, numVoiture, km);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEntretien")]
		public ISingleResult<GetEntretienResult> GetEntretien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numMoteur)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numMoteur);
			return ((ISingleResult<GetEntretienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteDetail")]
		public int DeleteDetail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMotor")]
		public int DeleteMotor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteEntretien")]
		public int DeleteEntretien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetConsommation")]
		public ISingleResult<GetConsommationResult> GetConsommation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numMoteur)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numMoteur);
			return ((ISingleResult<GetConsommationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteConsommation")]
		public int DeleteConsommation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TConsommation")]
	public partial class TConsommation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numConsommation;
		
		private int _numMoteur;
		
		private float _litre;
		
		private float _cout;
		
		private int _kmC;
		
		private EntityRef<TMoteur> _TMoteur;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumConsommationChanging(int value);
    partial void OnnumConsommationChanged();
    partial void OnnumMoteurChanging(int value);
    partial void OnnumMoteurChanged();
    partial void OnlitreChanging(float value);
    partial void OnlitreChanged();
    partial void OncoutChanging(float value);
    partial void OncoutChanged();
    partial void OnkmCChanging(int value);
    partial void OnkmCChanged();
    #endregion
		
		public TConsommation()
		{
			this._TMoteur = default(EntityRef<TMoteur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numConsommation", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numConsommation
		{
			get
			{
				return this._numConsommation;
			}
			set
			{
				if ((this._numConsommation != value))
				{
					this.OnnumConsommationChanging(value);
					this.SendPropertyChanging();
					this._numConsommation = value;
					this.SendPropertyChanged("numConsommation");
					this.OnnumConsommationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					if (this._TMoteur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnumMoteurChanging(value);
					this.SendPropertyChanging();
					this._numMoteur = value;
					this.SendPropertyChanged("numMoteur");
					this.OnnumMoteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_litre", DbType="Real NOT NULL")]
		public float litre
		{
			get
			{
				return this._litre;
			}
			set
			{
				if ((this._litre != value))
				{
					this.OnlitreChanging(value);
					this.SendPropertyChanging();
					this._litre = value;
					this.SendPropertyChanged("litre");
					this.OnlitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cout", DbType="Real NOT NULL")]
		public float cout
		{
			get
			{
				return this._cout;
			}
			set
			{
				if ((this._cout != value))
				{
					this.OncoutChanging(value);
					this.SendPropertyChanging();
					this._cout = value;
					this.SendPropertyChanged("cout");
					this.OncoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kmC", DbType="Int NOT NULL")]
		public int kmC
		{
			get
			{
				return this._kmC;
			}
			set
			{
				if ((this._kmC != value))
				{
					this.OnkmCChanging(value);
					this.SendPropertyChanging();
					this._kmC = value;
					this.SendPropertyChanged("kmC");
					this.OnkmCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TConsommation", Storage="_TMoteur", ThisKey="numMoteur", OtherKey="numMoteur", IsForeignKey=true)]
		public TMoteur TMoteur
		{
			get
			{
				return this._TMoteur.Entity;
			}
			set
			{
				TMoteur previousValue = this._TMoteur.Entity;
				if (((previousValue != value) 
							|| (this._TMoteur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMoteur.Entity = null;
						previousValue.TConsommation.Remove(this);
					}
					this._TMoteur.Entity = value;
					if ((value != null))
					{
						value.TConsommation.Add(this);
						this._numMoteur = value.numMoteur;
					}
					else
					{
						this._numMoteur = default(int);
					}
					this.SendPropertyChanged("TMoteur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDetailMoteur")]
	public partial class TDetailMoteur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numVoiture;
		
		private int _numMoteur;
		
		private int _km;
		
		private EntityRef<TMoteur> _TMoteur;
		
		private EntityRef<TVoiture> _TVoiture;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumVoitureChanging(int value);
    partial void OnnumVoitureChanged();
    partial void OnnumMoteurChanging(int value);
    partial void OnnumMoteurChanged();
    partial void OnkmChanging(int value);
    partial void OnkmChanged();
    #endregion
		
		public TDetailMoteur()
		{
			this._TMoteur = default(EntityRef<TMoteur>);
			this._TVoiture = default(EntityRef<TVoiture>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVoiture", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numVoiture
		{
			get
			{
				return this._numVoiture;
			}
			set
			{
				if ((this._numVoiture != value))
				{
					if (this._TVoiture.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnumVoitureChanging(value);
					this.SendPropertyChanging();
					this._numVoiture = value;
					this.SendPropertyChanged("numVoiture");
					this.OnnumVoitureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					if (this._TMoteur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnumMoteurChanging(value);
					this.SendPropertyChanging();
					this._numMoteur = value;
					this.SendPropertyChanged("numMoteur");
					this.OnnumMoteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km", DbType="Int NOT NULL")]
		public int km
		{
			get
			{
				return this._km;
			}
			set
			{
				if ((this._km != value))
				{
					this.OnkmChanging(value);
					this.SendPropertyChanging();
					this._km = value;
					this.SendPropertyChanged("km");
					this.OnkmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TDetailMoteur", Storage="_TMoteur", ThisKey="numMoteur", OtherKey="numMoteur", IsForeignKey=true)]
		public TMoteur TMoteur
		{
			get
			{
				return this._TMoteur.Entity;
			}
			set
			{
				TMoteur previousValue = this._TMoteur.Entity;
				if (((previousValue != value) 
							|| (this._TMoteur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMoteur.Entity = null;
						previousValue.TDetailMoteur.Remove(this);
					}
					this._TMoteur.Entity = value;
					if ((value != null))
					{
						value.TDetailMoteur.Add(this);
						this._numMoteur = value.numMoteur;
					}
					else
					{
						this._numMoteur = default(int);
					}
					this.SendPropertyChanged("TMoteur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TVoiture_TDetailMoteur", Storage="_TVoiture", ThisKey="numVoiture", OtherKey="numVoiture", IsForeignKey=true)]
		public TVoiture TVoiture
		{
			get
			{
				return this._TVoiture.Entity;
			}
			set
			{
				TVoiture previousValue = this._TVoiture.Entity;
				if (((previousValue != value) 
							|| (this._TVoiture.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TVoiture.Entity = null;
						previousValue.TDetailMoteur.Remove(this);
					}
					this._TVoiture.Entity = value;
					if ((value != null))
					{
						value.TDetailMoteur.Add(this);
						this._numVoiture = value.numVoiture;
					}
					else
					{
						this._numVoiture = default(int);
					}
					this.SendPropertyChanged("TVoiture");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMoteur")]
	public partial class TMoteur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numMoteur;
		
		private string _carburant;
		
		private int _cylindre;
		
		private int _puissance;
		
		private EntitySet<TConsommation> _TConsommation;
		
		private EntitySet<TDetailMoteur> _TDetailMoteur;
		
		private EntitySet<TEntretien> _TEntretien;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumMoteurChanging(int value);
    partial void OnnumMoteurChanged();
    partial void OncarburantChanging(string value);
    partial void OncarburantChanged();
    partial void OncylindreChanging(int value);
    partial void OncylindreChanged();
    partial void OnpuissanceChanging(int value);
    partial void OnpuissanceChanged();
    #endregion
		
		public TMoteur()
		{
			this._TConsommation = new EntitySet<TConsommation>(new Action<TConsommation>(this.attach_TConsommation), new Action<TConsommation>(this.detach_TConsommation));
			this._TDetailMoteur = new EntitySet<TDetailMoteur>(new Action<TDetailMoteur>(this.attach_TDetailMoteur), new Action<TDetailMoteur>(this.detach_TDetailMoteur));
			this._TEntretien = new EntitySet<TEntretien>(new Action<TEntretien>(this.attach_TEntretien), new Action<TEntretien>(this.detach_TEntretien));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					this.OnnumMoteurChanging(value);
					this.SendPropertyChanging();
					this._numMoteur = value;
					this.SendPropertyChanged("numMoteur");
					this.OnnumMoteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carburant", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string carburant
		{
			get
			{
				return this._carburant;
			}
			set
			{
				if ((this._carburant != value))
				{
					this.OncarburantChanging(value);
					this.SendPropertyChanging();
					this._carburant = value;
					this.SendPropertyChanged("carburant");
					this.OncarburantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cylindre", DbType="Int NOT NULL")]
		public int cylindre
		{
			get
			{
				return this._cylindre;
			}
			set
			{
				if ((this._cylindre != value))
				{
					this.OncylindreChanging(value);
					this.SendPropertyChanging();
					this._cylindre = value;
					this.SendPropertyChanged("cylindre");
					this.OncylindreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puissance", DbType="Int NOT NULL")]
		public int puissance
		{
			get
			{
				return this._puissance;
			}
			set
			{
				if ((this._puissance != value))
				{
					this.OnpuissanceChanging(value);
					this.SendPropertyChanging();
					this._puissance = value;
					this.SendPropertyChanged("puissance");
					this.OnpuissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TConsommation", Storage="_TConsommation", ThisKey="numMoteur", OtherKey="numMoteur")]
		public EntitySet<TConsommation> TConsommation
		{
			get
			{
				return this._TConsommation;
			}
			set
			{
				this._TConsommation.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TDetailMoteur", Storage="_TDetailMoteur", ThisKey="numMoteur", OtherKey="numMoteur")]
		public EntitySet<TDetailMoteur> TDetailMoteur
		{
			get
			{
				return this._TDetailMoteur;
			}
			set
			{
				this._TDetailMoteur.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TEntretien", Storage="_TEntretien", ThisKey="numMoteur", OtherKey="numMoteur")]
		public EntitySet<TEntretien> TEntretien
		{
			get
			{
				return this._TEntretien;
			}
			set
			{
				this._TEntretien.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TConsommation(TConsommation entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = this;
		}
		
		private void detach_TConsommation(TConsommation entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = null;
		}
		
		private void attach_TDetailMoteur(TDetailMoteur entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = this;
		}
		
		private void detach_TDetailMoteur(TDetailMoteur entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = null;
		}
		
		private void attach_TEntretien(TEntretien entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = this;
		}
		
		private void detach_TEntretien(TEntretien entity)
		{
			this.SendPropertyChanging();
			entity.TMoteur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUtilisateur")]
	public partial class TUtilisateur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numUtil;
		
		private string _pseudo;
		
		private string _mdp;
		
		private string _nom;
		
		private string _prenom;
		
		private string _email;
		
		private EntitySet<TVoiture> _TVoiture;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumUtilChanging(int value);
    partial void OnnumUtilChanged();
    partial void OnpseudoChanging(string value);
    partial void OnpseudoChanged();
    partial void OnmdpChanging(string value);
    partial void OnmdpChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public TUtilisateur()
		{
			this._TVoiture = new EntitySet<TVoiture>(new Action<TVoiture>(this.attach_TVoiture), new Action<TVoiture>(this.detach_TVoiture));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUtil", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numUtil
		{
			get
			{
				return this._numUtil;
			}
			set
			{
				if ((this._numUtil != value))
				{
					this.OnnumUtilChanging(value);
					this.SendPropertyChanging();
					this._numUtil = value;
					this.SendPropertyChanged("numUtil");
					this.OnnumUtilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this.OnpseudoChanging(value);
					this.SendPropertyChanging();
					this._pseudo = value;
					this.SendPropertyChanged("pseudo");
					this.OnpseudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mdp", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mdp
		{
			get
			{
				return this._mdp;
			}
			set
			{
				if ((this._mdp != value))
				{
					this.OnmdpChanging(value);
					this.SendPropertyChanging();
					this._mdp = value;
					this.SendPropertyChanged("mdp");
					this.OnmdpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUtilisateur_TVoiture", Storage="_TVoiture", ThisKey="numUtil", OtherKey="numUtil")]
		public EntitySet<TVoiture> TVoiture
		{
			get
			{
				return this._TVoiture;
			}
			set
			{
				this._TVoiture.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TVoiture(TVoiture entity)
		{
			this.SendPropertyChanging();
			entity.TUtilisateur = this;
		}
		
		private void detach_TVoiture(TVoiture entity)
		{
			this.SendPropertyChanging();
			entity.TUtilisateur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TVoiture")]
	public partial class TVoiture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numVoiture;
		
		private int _numUtil;
		
		private string _marque;
		
		private string _modele;
		
		private string _type;
		
		private string _couleur;
		
		private int _annee;
		
		private EntitySet<TDetailMoteur> _TDetailMoteur;
		
		private EntityRef<TUtilisateur> _TUtilisateur;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumVoitureChanging(int value);
    partial void OnnumVoitureChanged();
    partial void OnnumUtilChanging(int value);
    partial void OnnumUtilChanged();
    partial void OnmarqueChanging(string value);
    partial void OnmarqueChanged();
    partial void OnmodeleChanging(string value);
    partial void OnmodeleChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OncouleurChanging(string value);
    partial void OncouleurChanged();
    partial void OnanneeChanging(int value);
    partial void OnanneeChanged();
    #endregion
		
		public TVoiture()
		{
			this._TDetailMoteur = new EntitySet<TDetailMoteur>(new Action<TDetailMoteur>(this.attach_TDetailMoteur), new Action<TDetailMoteur>(this.detach_TDetailMoteur));
			this._TUtilisateur = default(EntityRef<TUtilisateur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVoiture", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numVoiture
		{
			get
			{
				return this._numVoiture;
			}
			set
			{
				if ((this._numVoiture != value))
				{
					this.OnnumVoitureChanging(value);
					this.SendPropertyChanging();
					this._numVoiture = value;
					this.SendPropertyChanged("numVoiture");
					this.OnnumVoitureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUtil", DbType="Int NOT NULL")]
		public int numUtil
		{
			get
			{
				return this._numUtil;
			}
			set
			{
				if ((this._numUtil != value))
				{
					if (this._TUtilisateur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnumUtilChanging(value);
					this.SendPropertyChanging();
					this._numUtil = value;
					this.SendPropertyChanged("numUtil");
					this.OnnumUtilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marque
		{
			get
			{
				return this._marque;
			}
			set
			{
				if ((this._marque != value))
				{
					this.OnmarqueChanging(value);
					this.SendPropertyChanging();
					this._marque = value;
					this.SendPropertyChanged("marque");
					this.OnmarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modele", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modele
		{
			get
			{
				return this._modele;
			}
			set
			{
				if ((this._modele != value))
				{
					this.OnmodeleChanging(value);
					this.SendPropertyChanging();
					this._modele = value;
					this.SendPropertyChanged("modele");
					this.OnmodeleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_couleur", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string couleur
		{
			get
			{
				return this._couleur;
			}
			set
			{
				if ((this._couleur != value))
				{
					this.OncouleurChanging(value);
					this.SendPropertyChanging();
					this._couleur = value;
					this.SendPropertyChanged("couleur");
					this.OncouleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annee", DbType="Int NOT NULL")]
		public int annee
		{
			get
			{
				return this._annee;
			}
			set
			{
				if ((this._annee != value))
				{
					this.OnanneeChanging(value);
					this.SendPropertyChanging();
					this._annee = value;
					this.SendPropertyChanged("annee");
					this.OnanneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TVoiture_TDetailMoteur", Storage="_TDetailMoteur", ThisKey="numVoiture", OtherKey="numVoiture")]
		public EntitySet<TDetailMoteur> TDetailMoteur
		{
			get
			{
				return this._TDetailMoteur;
			}
			set
			{
				this._TDetailMoteur.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUtilisateur_TVoiture", Storage="_TUtilisateur", ThisKey="numUtil", OtherKey="numUtil", IsForeignKey=true)]
		public TUtilisateur TUtilisateur
		{
			get
			{
				return this._TUtilisateur.Entity;
			}
			set
			{
				TUtilisateur previousValue = this._TUtilisateur.Entity;
				if (((previousValue != value) 
							|| (this._TUtilisateur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUtilisateur.Entity = null;
						previousValue.TVoiture.Remove(this);
					}
					this._TUtilisateur.Entity = value;
					if ((value != null))
					{
						value.TVoiture.Add(this);
						this._numUtil = value.numUtil;
					}
					else
					{
						this._numUtil = default(int);
					}
					this.SendPropertyChanged("TUtilisateur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TDetailMoteur(TDetailMoteur entity)
		{
			this.SendPropertyChanging();
			entity.TVoiture = this;
		}
		
		private void detach_TDetailMoteur(TDetailMoteur entity)
		{
			this.SendPropertyChanging();
			entity.TVoiture = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEntretien")]
	public partial class TEntretien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numEntretient;
		
		private int _numMoteur;
		
		private System.DateTime _date;
		
		private int _kmE;
		
		private string _info;
		
		private EntityRef<TMoteur> _TMoteur;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumEntretientChanging(int value);
    partial void OnnumEntretientChanged();
    partial void OnnumMoteurChanging(int value);
    partial void OnnumMoteurChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OnkmEChanging(int value);
    partial void OnkmEChanged();
    partial void OninfoChanging(string value);
    partial void OninfoChanged();
    #endregion
		
		public TEntretien()
		{
			this._TMoteur = default(EntityRef<TMoteur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numEntretient", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numEntretient
		{
			get
			{
				return this._numEntretient;
			}
			set
			{
				if ((this._numEntretient != value))
				{
					this.OnnumEntretientChanging(value);
					this.SendPropertyChanging();
					this._numEntretient = value;
					this.SendPropertyChanged("numEntretient");
					this.OnnumEntretientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					if (this._TMoteur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnumMoteurChanging(value);
					this.SendPropertyChanging();
					this._numMoteur = value;
					this.SendPropertyChanged("numMoteur");
					this.OnnumMoteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kmE", DbType="Int NOT NULL")]
		public int kmE
		{
			get
			{
				return this._kmE;
			}
			set
			{
				if ((this._kmE != value))
				{
					this.OnkmEChanging(value);
					this.SendPropertyChanging();
					this._kmE = value;
					this.SendPropertyChanged("kmE");
					this.OnkmEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string info
		{
			get
			{
				return this._info;
			}
			set
			{
				if ((this._info != value))
				{
					this.OninfoChanging(value);
					this.SendPropertyChanging();
					this._info = value;
					this.SendPropertyChanged("info");
					this.OninfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMoteur_TEntretien", Storage="_TMoteur", ThisKey="numMoteur", OtherKey="numMoteur", IsForeignKey=true)]
		public TMoteur TMoteur
		{
			get
			{
				return this._TMoteur.Entity;
			}
			set
			{
				TMoteur previousValue = this._TMoteur.Entity;
				if (((previousValue != value) 
							|| (this._TMoteur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMoteur.Entity = null;
						previousValue.TEntretien.Remove(this);
					}
					this._TMoteur.Entity = value;
					if ((value != null))
					{
						value.TEntretien.Add(this);
						this._numMoteur = value.numMoteur;
					}
					else
					{
						this._numMoteur = default(int);
					}
					this.SendPropertyChanged("TMoteur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetNumMoteurResult
	{
		
		private int _numMoteur;
		
		public GetNumMoteurResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					this._numMoteur = value;
				}
			}
		}
	}
	
	public partial class GetNumUserResult
	{
		
		private int _numUtil;
		
		public GetNumUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUtil", DbType="Int NOT NULL")]
		public int numUtil
		{
			get
			{
				return this._numUtil;
			}
			set
			{
				if ((this._numUtil != value))
				{
					this._numUtil = value;
				}
			}
		}
	}
	
	public partial class GetUserResult
	{
		
		private int _numUtil;
		
		private string _pseudo;
		
		private string _mdp;
		
		private string _nom;
		
		private string _prenom;
		
		private string _email;
		
		public GetUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUtil", DbType="Int NOT NULL")]
		public int numUtil
		{
			get
			{
				return this._numUtil;
			}
			set
			{
				if ((this._numUtil != value))
				{
					this._numUtil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this._pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mdp", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mdp
		{
			get
			{
				return this._mdp;
			}
			set
			{
				if ((this._mdp != value))
				{
					this._mdp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this._prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	public partial class SearchCarResult
	{
		
		private int _numVoiture;
		
		private int _numUtil;
		
		private string _marque;
		
		private string _modele;
		
		private string _type;
		
		private string _couleur;
		
		private int _annee;
		
		public SearchCarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVoiture", DbType="Int NOT NULL")]
		public int numVoiture
		{
			get
			{
				return this._numVoiture;
			}
			set
			{
				if ((this._numVoiture != value))
				{
					this._numVoiture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numUtil", DbType="Int NOT NULL")]
		public int numUtil
		{
			get
			{
				return this._numUtil;
			}
			set
			{
				if ((this._numUtil != value))
				{
					this._numUtil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marque
		{
			get
			{
				return this._marque;
			}
			set
			{
				if ((this._marque != value))
				{
					this._marque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modele", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modele
		{
			get
			{
				return this._modele;
			}
			set
			{
				if ((this._modele != value))
				{
					this._modele = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_couleur", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string couleur
		{
			get
			{
				return this._couleur;
			}
			set
			{
				if ((this._couleur != value))
				{
					this._couleur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annee", DbType="Int NOT NULL")]
		public int annee
		{
			get
			{
				return this._annee;
			}
			set
			{
				if ((this._annee != value))
				{
					this._annee = value;
				}
			}
		}
	}
	
	public partial class SearchUserResult
	{
		
		private string _pseudo;
		
		public SearchUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pseudo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pseudo
		{
			get
			{
				return this._pseudo;
			}
			set
			{
				if ((this._pseudo != value))
				{
					this._pseudo = value;
				}
			}
		}
	}
	
	public partial class GetNumVoitureResult
	{
		
		private int _numVoiture;
		
		public GetNumVoitureResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVoiture", DbType="Int NOT NULL")]
		public int numVoiture
		{
			get
			{
				return this._numVoiture;
			}
			set
			{
				if ((this._numVoiture != value))
				{
					this._numVoiture = value;
				}
			}
		}
	}
	
	public partial class GetVoitureResult
	{
		
		private int _numVoiture;
		
		private string _marque;
		
		private string _modele;
		
		private string _type;
		
		private string _couleur;
		
		private int _annee;
		
		private int _km;
		
		private string _carburant;
		
		private int _cylindre;
		
		private int _puissance;
		
		private int _numMoteur;
		
		public GetVoitureResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVoiture", DbType="Int NOT NULL")]
		public int numVoiture
		{
			get
			{
				return this._numVoiture;
			}
			set
			{
				if ((this._numVoiture != value))
				{
					this._numVoiture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marque
		{
			get
			{
				return this._marque;
			}
			set
			{
				if ((this._marque != value))
				{
					this._marque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modele", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modele
		{
			get
			{
				return this._modele;
			}
			set
			{
				if ((this._modele != value))
				{
					this._modele = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_couleur", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string couleur
		{
			get
			{
				return this._couleur;
			}
			set
			{
				if ((this._couleur != value))
				{
					this._couleur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annee", DbType="Int NOT NULL")]
		public int annee
		{
			get
			{
				return this._annee;
			}
			set
			{
				if ((this._annee != value))
				{
					this._annee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km", DbType="Int NOT NULL")]
		public int km
		{
			get
			{
				return this._km;
			}
			set
			{
				if ((this._km != value))
				{
					this._km = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carburant", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string carburant
		{
			get
			{
				return this._carburant;
			}
			set
			{
				if ((this._carburant != value))
				{
					this._carburant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cylindre", DbType="Int NOT NULL")]
		public int cylindre
		{
			get
			{
				return this._cylindre;
			}
			set
			{
				if ((this._cylindre != value))
				{
					this._cylindre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puissance", DbType="Int NOT NULL")]
		public int puissance
		{
			get
			{
				return this._puissance;
			}
			set
			{
				if ((this._puissance != value))
				{
					this._puissance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					this._numMoteur = value;
				}
			}
		}
	}
	
	public partial class GetEntretienResult
	{
		
		private int _numEntretient;
		
		private int _numMoteur;
		
		private System.DateTime _date;
		
		private int _kmE;
		
		private string _info;
		
		public GetEntretienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numEntretient", DbType="Int NOT NULL")]
		public int numEntretient
		{
			get
			{
				return this._numEntretient;
			}
			set
			{
				if ((this._numEntretient != value))
				{
					this._numEntretient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					this._numMoteur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kmE", DbType="Int NOT NULL")]
		public int kmE
		{
			get
			{
				return this._kmE;
			}
			set
			{
				if ((this._kmE != value))
				{
					this._kmE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string info
		{
			get
			{
				return this._info;
			}
			set
			{
				if ((this._info != value))
				{
					this._info = value;
				}
			}
		}
	}
	
	public partial class GetConsommationResult
	{
		
		private int _numConsommation;
		
		private int _numMoteur;
		
		private float _litre;
		
		private float _cout;
		
		private int _kmC;
		
		public GetConsommationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numConsommation", DbType="Int NOT NULL")]
		public int numConsommation
		{
			get
			{
				return this._numConsommation;
			}
			set
			{
				if ((this._numConsommation != value))
				{
					this._numConsommation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMoteur", DbType="Int NOT NULL")]
		public int numMoteur
		{
			get
			{
				return this._numMoteur;
			}
			set
			{
				if ((this._numMoteur != value))
				{
					this._numMoteur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_litre", DbType="Real NOT NULL")]
		public float litre
		{
			get
			{
				return this._litre;
			}
			set
			{
				if ((this._litre != value))
				{
					this._litre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cout", DbType="Real NOT NULL")]
		public float cout
		{
			get
			{
				return this._cout;
			}
			set
			{
				if ((this._cout != value))
				{
					this._cout = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kmC", DbType="Int NOT NULL")]
		public int kmC
		{
			get
			{
				return this._kmC;
			}
			set
			{
				if ((this._kmC != value))
				{
					this._kmC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
